"""order

Revision ID: 68d43364a111
Revises: a8a77f38708e
Create Date: 2025-12-30 10:55:16.766934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d43364a111'
down_revision: Union[str, Sequence[str], None] = 'a8a77f38708e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'cart_id',
               existing_type=sa.INTEGER())
    op.alter_column('orders', 'total_price',
               existing_type=sa.DECIMAL(precision=10, scale=2))
    op.alter_column('orders', 'payment_type',
               existing_type=sa.VARCHAR(length=16))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('orders', 'total_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('order_items', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
