"""Order new migration

Revision ID: 7e29923d1563
Revises: baff0be6836a
Create Date: 2025-12-28 17:16:32.671615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e29923d1563'
down_revision: Union[str, Sequence[str], None] = 'baff0be6836a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'cart_id',
               existing_type=sa.INTEGER())
    op.add_column('orders', sa.Column('total_price', sa.DECIMAL(precision=10, scale=2)))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    op.alter_column('order_items', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
