"""Payments

Revision ID: a8a77f38708e
Revises: 7e29923d1563
Create Date: 2025-12-28 19:26:07.195026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a77f38708e'
down_revision: Union[str, Sequence[str], None] = '7e29923d1563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'cart_id',
               existing_type=sa.INTEGER())
    op.add_column('orders', sa.Column('total_price', sa.DECIMAL(precision=10, scale=2)))
    op.alter_column('orders', 'payment_type',
               existing_type=sa.VARCHAR(length=16))
    op.drop_column('payments', 'payment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_type', sa.VARCHAR(length=16), nullable=False))
    op.alter_column('orders', 'payment_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.drop_column('orders', 'total_price')
    op.alter_column('order_items', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
